package com._try.heart;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Patient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "PATIENT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PATIENT_ID_GENERATOR", sequenceName = "PATIENT_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Age")
	private double age;

	@org.kie.api.definition.type.Label("Sexe")
	private java.lang.String sexe;

	@org.kie.api.definition.type.Label("Type Douleur")
	private java.lang.String type_douleur;

	@org.kie.api.definition.type.Label("Pression")
	private double pression;

	@org.kie.api.definition.type.Label("Cholester")
	private double cholester;

	@org.kie.api.definition.type.Label("Sucre")
	private java.lang.String sucre;

	@org.kie.api.definition.type.Label("Electro")
	private java.lang.String electro;

	@org.kie.api.definition.type.Label("Taux Max")
	private double taux_max;

	@org.kie.api.definition.type.Label("Angine")
	private java.lang.String angine;

	@org.kie.api.definition.type.Label("Depression")
	private double depression;

	@org.kie.api.definition.type.Label("Pic")
	private double pic;

	@org.kie.api.definition.type.Label("Vaisseau")
	private java.lang.String vaisseau;

	@org.kie.api.definition.type.Label("Cœur")
	private java.lang.String coeur;

	public Patient() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public double getAge() {
		return this.age;
	}

	public void setAge(double age) {
		this.age = age;
	}

	public java.lang.String getSexe() {
		return this.sexe;
	}

	public void setSexe(java.lang.String sexe) {
		this.sexe = sexe;
	}

	public java.lang.String getType_douleur() {
		return this.type_douleur;
	}

	public void setType_douleur(java.lang.String type_douleur) {
		this.type_douleur = type_douleur;
	}

	public double getPression() {
		return this.pression;
	}

	public void setPression(double pression) {
		this.pression = pression;
	}

	public double getCholester() {
		return this.cholester;
	}

	public void setCholester(double cholester) {
		this.cholester = cholester;
	}

	public java.lang.String getSucre() {
		return this.sucre;
	}

	public void setSucre(java.lang.String sucre) {
		this.sucre = sucre;
	}

	public java.lang.String getElectro() {
		return this.electro;
	}

	public void setElectro(java.lang.String electro) {
		this.electro = electro;
	}

	public double getTaux_max() {
		return this.taux_max;
	}

	public void setTaux_max(double taux_max) {
		this.taux_max = taux_max;
	}

	public java.lang.String getAngine() {
		return this.angine;
	}

	public void setAngine(java.lang.String angine) {
		this.angine = angine;
	}

	public double getDepression() {
		return this.depression;
	}

	public void setDepression(double depression) {
		this.depression = depression;
	}

	public double getPic() {
		return this.pic;
	}

	public void setPic(double pic) {
		this.pic = pic;
	}

	public java.lang.String getVaisseau() {
		return this.vaisseau;
	}

	public void setVaisseau(java.lang.String vaisseau) {
		this.vaisseau = vaisseau;
	}

	public java.lang.String getCoeur() {
		return this.coeur;
	}

	public void setCoeur(java.lang.String coeur) {
		this.coeur = coeur;
	}

	public Patient(java.lang.Long id, double age, java.lang.String sexe,
			java.lang.String type_douleur, double pression, double cholester,
			java.lang.String sucre, java.lang.String electro, double taux_max,
			java.lang.String angine, double depression, double pic,
			java.lang.String vaisseau, java.lang.String coeur) {
		this.id = id;
		this.age = age;
		this.sexe = sexe;
		this.type_douleur = type_douleur;
		this.pression = pression;
		this.cholester = cholester;
		this.sucre = sucre;
		this.electro = electro;
		this.taux_max = taux_max;
		this.angine = angine;
		this.depression = depression;
		this.pic = pic;
		this.vaisseau = vaisseau;
		this.coeur = coeur;
	}

}